### ISSUE TITLE
TS Error: GraphQLDocumentError: Unknown type "ImgixFixed"

### ISSUE THREAD

**Issue by alexanderbluhm** [prismicio/prismic-gatsby#515] opened 2022-07-15 07:48 UTC
### Versions

- gatsby-source-prismic: ^5.2.9
- gatsby-plugin-prismic-previews: "^5.2.8"
- node: v16.15.0

### Reproduction

Minimal reproduction repository: https://github.com/alexanderbluhm/gatsby-ts-prismic-error

### Steps to reproduce

1. Initialize a new Gatsby TS project `npm init gatsby -ts` (No CMS, Add PostCSS, Responsive Images, React Helmet, Manifest)   Of course it works now with `npm start`
2. `npm i -D gatsby-source-prismic`
3. `npm start`
(The same happens if I only install `gatsby-plugin-prismic-previews`)

### What is expected?

I expect that the project starts without any errors and correct type generation.

### What is actually happening?

I get this error when starting the dev server:
```
ERROR #12100  GRAPHQL

There was an error while trying to generate TS types from your GraphQL queries:

    AggregateError: GraphQL Document Validation failed with 300 errors;
  Error 0: GraphQLDocumentError: Unknown type "ImgixFixed".
    at undefined:2:32
  ...
```

**Comment by alexanderbluhm** [comment] 2022-07-18 10:17
It is working now if I add the plugin to the Gatsby config and connect it to a Prismic repository with two published documents.   
However, it shouldn't throw a type error when only adding the packages.

**Comment by angeloashmore** [comment] 2022-07-19 23:59
@alexanderbluhm Thanks for following up after finding a semi-solution.

I believe this happens because Gatsby looks through `node_modules` for any `` graphql`...` `` queries when generating TypeScript types.

`gatsby-source-prismic` defines its own GraphQL fragments with `` graphql`...` `` in [`gatsby-source-prismic/fragments.js`](https://github.com/prismicio/prismic-gatsby/blob/45a2db5ff798a34f1c28d340a907f5064f347978/packages/gatsby-source-prismic/fragments.js), which uses `ImgixFixed`. The `ImgixFixed` GraphQL type won't exist unless the plugin is loaded by adding it to `gatsby-config.js`.

This isn't something that can be fixed in the plugin, and I would consider it a bug in Gatsby's new TypeScript types generation. Gatsby shouldn't read plugins not added to `gatsby-config.js`.

If the Gatsby team decides it is not a bug, then I think we would need to treat it as a non-issue and require `gatsby-source-prismic` to be added to `gatsby-config.js` if it is installed.

**Closed** 2022-07-20 00:00 UTC
Labels: bug
