### ISSUE TITLE
Url decoding special characters

### ISSUE THREAD

**Issue by rundas912** [prismicio/prismic-gatsby#451] opened 2021-09-29 09:23 UTC
Hello,

As mentioned in issue #404 and #194, I also have a problem with the plugin decoding special characters like the "+" sign or the "%" sign messing up my urls and giving me 404. I thought this was solved with #405 but it doesn't seem to work on my side.

### Versions

- gatsby-source-prismic: 4.1.6
- node: v15.0.1
- gatsby : v3.14.0

**Comment by angeloashmore** [comment] 2021-10-01 03:07
Hi @rundas912, can you provide an example URL? Both the working URL directly from Prismic and the resulting broken URL?

With these, I can test where the plugin is improperly processing special characters.

Thank you!

**Comment by rundas912** [comment] 2021-10-01 06:47
hello @angeloashmore , sorry I should have been more precise. For example, here is the url of my image set in prismic :
"https://images.prismic.io/utopixwebsite/9480e245-cb7f-4b7c-97e6-683db41736ca_Illustrations+emojis+L.png?auto=compress,format&w=900"

And here is what I get when I query the url of the image in my app : 
"https://images.prismic.io/utopixwebsite/9480e245-cb7f-4b7c-97e6-683db41736ca_Illustrations%20emojis%20L.png?ixlib=gatsbyFP&auto=compress%2Cformat&fit=max&q=50"

As you can see the + sign is replaced by %20 for example

**Comment by rundas912** [comment] 2021-10-01 07:05
hello @angeloashmore , sorry I should have been more precise. 

For example, here is the url of my image set in prismic :
"https://images.prismic.io/utopixwebsite/9480e245-cb7f-4b7c-97e6-683db41736ca_Illustrations+emojis+L.png?auto=compress,format&w=900"

And here is what I get when I query the url of the image in my app :
"https://images.prismic.io/utopixwebsite/9480e245-cb7f-4b7c-97e6-683db41736ca_Illustrations%20emojis%20L.png?ixlib=gatsbyFP&auto=compress%2Cformat&fit=max&q=50"

As you can see the + sign is replaced by %20 for example. I just noticed it does still work though if I use a simple <img> tag but I'm using react-imgix to display my image with seems to encode the character again => %20 becomes %2520 and that's where I get my 404 from (see this open issue https://github.com/imgix/react-imgix/issues/815)

**Comment by angeloashmore** [comment] 2021-10-01 19:57
Hey @rundas912, no problem, thanks for providing those details. 🙂

The issue comes from using react-imgix with the URLs from `gatsby-source-prismic`. Imgix expects all URLs to be decoded (e.g. `"%20"` should be a literal space, `" "`) and then outputs encoded URLs (`" "` will turn into `"%20"`).

Since we are using `@imgix/gatsby` in `gatsby-source-prismic` (which uses `@imgix/js-core` like `react-imgix`), the URLs are returned encoded.

If you continue using `react-imgix`, you will need to decode the images before passing them to the component.

```tsx
<Imgix
  src={decodeURIComponent(yourUrl)}
/>
```

Alternatively, you can use Gatsby's `gatsby-plugin-image`. It provides roughly the same functionality as `react-imgix`, but in a Gatsby-specific way. In your page query, you can query for `gatsbyImageData` and pass it to `<GatsbyImage>` without needing to worry about encoding/decoding URLs.

You can learn more about using `gatsby-plugin-image` with Prismic here: https://prismic.io/docs/technologies/template-images-gatsby#image-processing

I'm going to close this issue as the plugin itself is decoding/encoding URLs as designed, but we can continue the conversation here if you are still having trouble with it.

**Closed by angeloashmore** 2021-10-01 19:57 UTC
Labels: bug
