### ISSUE TITLE
Unpublished previews always 404ing

### ISSUE THREAD

**Issue by valtism** [prismicio/prismic-gatsby#431] opened 2021-08-18 01:25 UTC
`gatsby-source-prismic: 4.0.2`
`gatsby-plugin-prismic-previews: 4.0.3`
`node: v14.16.1`

I know this has been brought up in many issues already, but I have gone over each one multiple times and not been able to solve for my use-case.

Currently, I have previews working for published documents, but when I try to preview an unpublished document I always get the 404 page.

<details>
<summary>404.tsx</summary>
<p>

```tsx
import * as React from 'react';
import { PageProps, graphql } from 'gatsby';
import {
  withPrismicUnpublishedPreview,
  componentResolverFromMap,
} from 'gatsby-plugin-prismic-previews';
import BlogPage from '@templates/BlogPage';
import DocPage from '@templates/DocPage';
import Homepage from '@templates/Homepage';
import MarketingPage from '@templates/MarketingPage';
import Button from '@components/Button';
import MarketingLayout from '@components/MarketingLayout';
import { linkResolver } from '@utils/linkResolver';
import { PrismicNav, PrismicFooter } from '@typings/prismic-types';
import './styles.scss';

interface Props extends PageProps {
  data: {
    prismicNav?: PrismicNav;
    prismicFooter?: PrismicFooter;
  };
}

const ErrorMessage = () => {
  return (
    <section className={`not-found`}>
      <h1>404: Oops! This page does not exist.</h1>
      <Button iconType={'Arrow'} href={`/`}>
        Take Me Home
      </Button>
    </section>
  );
};

const NotFoundPage = ({ data }: Props) => {
  if (!data) return <ErrorMessage />;

  const nav = data.prismicNav;
  const footer = data.prismicFooter;

  return (
    <MarketingLayout nav={nav && nav.data} footer={footer && footer.data}>
      <ErrorMessage />
    </MarketingLayout>
  );
};

export const query = graphql`
  query notFoundPage($lang: String) {
    prismicNav(lang: { eq: $lang }) {
      ...NavFragment
    }
    prismicFooter(lang: { eq: $lang }) {
      ...FooterFragment
    }
  }
`;

export default withPrismicUnpublishedPreview(NotFoundPage, [
  {
    repositoryName: process.env.GATSBY_PRISMIC_REPO_NAME,
    linkResolver,
    componentResolver: componentResolverFromMap({
      blog_page: BlogPage,
      doc_page: DocPage,
      homepage: Homepage,
      marketing_page: MarketingPage,
    }),
  },
]);
```

</p>
</details>

<details>
<summary>DocPage.tsx</summary>
<p>

```tsx
import React from 'react';
import { graphql, PageProps } from 'gatsby';
import { withPrismicPreview } from 'gatsby-plugin-prismic-previews';
import DocContentLayout from '@components/DocContentLayout';
import DocLayout from '@components/DocLayout';
import { linkResolver } from '@utils/linkResolver';
import { DocIdMap } from '@utils/typings/custom';
import {
  PrismicDocPage,
  PrismicDocPageConnection,
  PrismicDocsSitemap,
  PrismicFooter,
} from '@typings/prismic-types';

interface Props extends PageProps {
  data: {
    prismicDocPage: PrismicDocPage;
    prismicDocsSitemap: PrismicDocsSitemap;
    allPrismicDocPage: PrismicDocPageConnection;
    prismicFooter: PrismicFooter;
  };
}

export const DocPageTemplate = ({ data }: Props) => {
  if (!data) return null;

  const docPage = data.prismicDocPage;
  const docsSitemap = data.prismicDocsSitemap;
  const footer = data.prismicFooter;

  const docIdMap: DocIdMap = data.allPrismicDocPage.nodes.reduce(
    (obj, item) => ({
      ...obj,
      [item.prismicId]: { title: item.data.title.text, url: item.url },
    }),
    {},
  );

  const orderedPageIds = docsSitemap.data.top_level_pages
    .map((page) => page.doc_page.id)
    .concat(
      docsSitemap.data.body.flatMap((group) =>
        group.items.map((page) => page.doc_page.id),
      ),
    );

  const docMetadata = {
    title: `${docPage.data.title.text} - Pry`,
    description: docPage.data.metadata_description.text,
    image: docPage.data.metadata_image.url,
  };

  return (
    <DocLayout
      docsSitemap={docsSitemap}
      footer={footer.data}
      docIdMap={docIdMap}
      docMetadata={docMetadata}
      activeUrl={docPage.url}
      firstDocUrl={docIdMap[orderedPageIds[0]].url}
    >
      <DocContentLayout
        docPage={docPage}
        docsSitemap={docsSitemap}
        orderedPageIds={orderedPageIds}
        docIdMap={docIdMap}
      />
    </DocLayout>
  );
};

export const query = graphql`
  query docPageQuery($uid: String, $lang: String) {
    prismicDocPage(uid: { eq: $uid }, lang: { eq: $lang }) {
      _previewable
      url
      uid
      type
      id
      prismicId
      lang
      alternate_languages {
        id
        type
        lang
        uid
      }
      data {
        title {
          text
        }
        body {
          ... on PrismicDocPageDataBodyDocsRichText {
            id
            slice_type
            slice_label
            primary {
              rich_text {
                raw
              }
            }
          }
          ... on PrismicDocPageDataBodyImportantBlockQuote {
            id
            slice_type
            slice_label
            primary {
              text {
                text
              }
              heading {
                text
              }
            }
          }
          ... on PrismicDocPageDataBodyDocsFullWidthImage {
            id
            slice_type
            slice_label
            primary {
              background_image_position
              image {
                url
                alt
              }
            }
          }
        }
        metadata_image {
          alt
          url
        }
        metadata_description {
          text
        }
      }
    }
    allPrismicDocPage {
      nodes {
        id
        prismicId
        url
        data {
          title {
            text
          }
        }
      }
    }
    prismicDocsSitemap(lang: { eq: $lang }) {
      ...PrismicDocsSitemapFragment
    }
    prismicFooter(lang: { eq: $lang }) {
      ...FooterFragment
    }
  }
`;

// @ts-ignore
export default withPrismicPreview(DocPageTemplate, [
  {
    repositoryName: process.env.GATSBY_PRISMIC_REPO_NAME,
    linkResolver,
  },
]);
```

</p>
</details>

<details>
<summary>gatsby-node.js</summary>
<p>

```js
const path = require('path');

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions;

  const pages = await graphql(`
    {
      allPrismicHomepage {
        nodes {
          id
          lang
          type
          url
        }
      }
      allPrismicDocPage {
        nodes {
          id
          uid
          lang
          type
          url
        }
      }
      allPrismicMarketingPage {
        nodes {
          id
          uid
          lang
          type
          url
        }
      }
      allPrismicBlogPage {
        nodes {
          id
          uid
          lang
          type
          url
        }
      }
    }
  `);

  pages.data.allPrismicHomepage.nodes.forEach((page) => {
    createPage({
      path: page.url,
      component: path.resolve(__dirname, 'src/templates/Homepage.tsx'),
      context: { ...page },
    });
  });

  pages.data.allPrismicDocPage.nodes.forEach((page) => {
    createPage({
      path: page.url,
      component: path.resolve(__dirname, 'src/templates/DocPage.tsx'),
      context: { ...page },
    });
  });

  pages.data.allPrismicMarketingPage.nodes.forEach((page) => {
    createPage({
      path: page.url,
      component: path.resolve(__dirname, 'src/templates/MarketingPage.tsx'),
      context: { ...page },
    });
  });

  pages.data.allPrismicBlogPage.nodes.forEach((page) => {
    createPage({
      path: page.url,
      component: path.resolve(__dirname, 'src/templates/BlogPage.tsx'),
      context: { ...page },
    });
  });

  createPage({
    path: 'privacy-policy',
    component: path.resolve(__dirname, 'src/templates/PrivacyPolicy.tsx'),
  });

  createPage({
    path: 'terms-of-service',
    component: path.resolve(__dirname, 'src/templates/TermsOfService.tsx'),
  });
};
```

</p>
</details>

I get no console errors.

In the network tab, I see the request to `http://localhost:8000/page-data/docs/unpublished-preview/page-data.json` return a 404 along with the data `{"path":"docs/unpublished-preview"}`, then a request to `http://localhost:8000/page-data/404.html/page-data.json` that succeeds.

After this, there is a call to `https://prydocs.prismic.io/toolbar/state` that has some information on the unpublished preview, like title, url and summary, but not the whole page.

Looking at the react dev tools Components tab I don't see the data in PrismicPreviewProvider either:

<details>
<summary>PrismicPreviewProvider</summary>
<p>

```json
[
  {
    "name": "Reducer",
    "value": {
      "previewState": "IDLE",
      "isBootstrapped": false,
      "nodes": "{}",
      "pluginOptionsStore": "{prydocs: {…}}",
      "typePathsStore": "{}",
      "repositoryConfigs": "[]"
    },
    "subHooks": [],
    "hookSource": {
      "lineNumber": 420,
      "functionName": "PrismicPreviewProvider",
      "fileName": "webpack-internal:///./node_modules/gatsby-plugin-prismic-previews/dist/index.js",
      "columnNumber": 71
    }
  },
  {
    "name": "LayoutEffect",
    "value": "ƒ () {}",
    "subHooks": [],
    "hookSource": {
      "lineNumber": 421,
      "functionName": "PrismicPreviewProvider",
      "fileName": "webpack-internal:///./node_modules/gatsby-plugin-prismic-previews/dist/index.js",
      "columnNumber": 57
    }
  }
]
```

</p>
</details>

I'm not sure what I am missing here. Any help would be greatly appreciated. 🙏

**Comment by angeloashmore** [comment] 2021-08-18 21:51
Hey @valtism, thanks for all the details. Everything in your code looks okay. If published previews are working okay, but unpublished previews are not, that makes this especially unusual.

There currently seems to be an issue with previews and the Prismic Toolbar right now. The issue is preventing previews from loading in some repositories (basically, the cookie used by the preview system is not getting set properly).

Your issue looks related to the toolbar issue since we can see in your provider that `isBootstrapped` is false. `isBootstrapped` tells you if the preview plugin detected a preview session and pulled all your documents.

I'm looking into the issue and will update you as I learn more. Thanks for your patience. 🙂

**Comment by valtism** [comment] 2021-08-31 03:10
I just realised that the site was still adding the toolbar via script tags. I removed these since we are now using the plugin, but the preview still is not working (totally cleaned app, cleared app memory and disabled cache). Getting a slightly different output in the Provider now:

```json
[
  {
    "name": "Reducer",
    "value": {
      "activeRepositoryName": "prydocs",
      "previewState": "RESOLVED",
      "isBootstrapped": false,
      "nodes": "{}",
      "pluginOptionsStore": "{prydocs: {…}}",
      "typePathsStore": "{}",
      "repositoryConfigs": "[]",
      "resolvedPath": "/blog/hi"
    },
    "subHooks": [],
    "hookSource": {
      "lineNumber": 420,
      "functionName": "PrismicPreviewProvider",
      "fileName": "webpack-internal:///./node_modules/gatsby-plugin-prismic-previews/dist/index.js",
      "columnNumber": 71
    }
  },
  {
    "name": "LayoutEffect",
    "value": "ƒ () {}",
    "subHooks": [],
    "hookSource": {
      "lineNumber": 421,
      "functionName": "PrismicPreviewProvider",
      "fileName": "webpack-internal:///./node_modules/gatsby-plugin-prismic-previews/dist/index.js",
      "columnNumber": 57
    }
  }
]
```

**Comment by angeloashmore** [comment] 2021-09-08 02:20
I'm going to close this issue as it turned out the error came from importing the Link Resolver incorrectly.

I've opened a new issue to provide a better warning: https://github.com/prismicio/prismic-gatsby/issues/442

**Closed by angeloashmore** 2021-09-08 02:20 UTC
Labels: bug, V4
