### ISSUE TITLE
Previews broken?

### ISSUE THREAD

**Issue by mrseanbaines** [prismicio/prismic-gatsby#430] opened 2021-08-17 15:58 UTC
_Also posted in [the community forum](https://community.prismic.io/t/can-not-set-up-previews-with-v4-gatsby-prismic-integration/6398/22?u=sean)_

Previews were working last week and today I noticed that they aren't any more. Not sure what I've changed, and I've tried rolling back to a previous version but still get the same results.

After clicking the preview button in Prismic, I get stuck on the `/preview` route without getting redirected. No console errors. Following the debugging advice in [this article](https://community.prismic.io/t/troubleshooting-previews/5449), I checked the preview cookie, but the value isn't a URL like the article says it should be, so I am guessing this is causing/contributing to the issue. I'm not sure what's causing this though or how to resolve it (if this is even the issue).

![image](https://user-images.githubusercontent.com/24367010/129760060-6880ef95-8253-4618-944a-2a2ab3f32b49.png)

### Versions
- gatsby-source-prismic: v4.0.1
- gatsby-plugin-prismic-previews: v4.0.1
- node: v14.17.1

### What is expected?
I should be able to preview documents and get redirected to the correct page

### What is actually happening?
I get stuck on the `/preview` route

**Comment by angeloashmore** [comment] 2021-08-18 22:10
Hey @mrseanbaines, thanks for posting on the forum as well. This seems to be a Prismic API issue rather than your code or the Gatsby plugins.

The team is investigating the issue, but for now there is no workaround to get previews working unfortunately.

In the mean time, you can create releases with your edits and rebuild your Gatsby site with the Release ID. See the [`releaseID` plugin option](https://prismic.io/docs/technologies/install-the-plugin-gatsby#3.-configure-the-plugin) for more details. This is not ideal, but it will at least allow you to preview content before publishing to your live site.

**Comment by benjaminwaterlot** [comment] 2021-08-19 08:58
Hello @angeloashmore, 

Just wanted to signal that we're experiencing the same problem and it's very concerning for our content team - do you have an estimate of the time to fix ? :)

**Comment by kb1995** [comment] 2021-08-19 13:27
Just wanted to flag that preview are broken in my client's Gatsby website. They kind of work, but are missing some rich text fields such as titles. I don't think there is the same problem for the other Nextjs websites which I manage

**Comment by benjaminwaterlot** [comment] 2021-08-19 16:41
@kb1995 do you think this is the same issue as https://github.com/prismicio/prismic-gatsby/issues/401 ?

Last time I checked, the plugin was indeed returning different data formats between the preview and published content (details and workaround in the issue).

**Comment by angeloashmore** [comment] 2021-08-19 19:44
@benjaminwaterlot Thanks for letting me know your repo is also experiencing the issue. It's definitely frustrating (it's also affecting my own projects). I don't have an estimate on when it will be fixed but the development team is aware of the issue.

FYI this is an issue for a group of Prismic repositories and not specific to Gatsby. The code in your project likely isn't broken if previews are currently not working.

I will post an update here as I learn more. Until then, please hang tight! 🙏

---

@kb1995 Missing content should not happen during a preview. The shape of the data should be the same during builds and previews (except for some differences in image handling). Can you confirm you are using the latest version of the plugin and test it again? If the same issue happens, could you open as separate issue with your project details? Thank you!

**Comment by kb1995** [comment] 2021-08-20 10:08
@angeloashmore I commented in #401

**Comment by inetdigital** [comment] 2021-08-20 14:21
@angeloashmore I am testing gatsby-source-prismic@4.0.0-beta.17 and gatsby-plugin-prismic-previews@4.1.0 on a new project for the first time today. Previews always get stuck on the /preview route and never resolve, I believe the same as other issues being reported. Am I to understand this is confirmed as being due to a Prismic API issue and there is no known fix currently?

**Comment by angeloashmore** [comment] 2021-08-20 18:16
@inetdigital That's correct, it is most likely due to a Prismic API issue. The dev team is currently figuring out the issue to find a fix. There is no workaround for now, unfortunately.

In your project, I would recommend updating to the latest versions to make sure everything works as expected.

- `gatsby-source-prismic`: `v4.1.0`
- `gatsby-plugin-prismic-previews`: `v4.1.0`

Thank you everyone for your patience 🙏

**Comment by benjaminwaterlot** [comment] 2021-08-23 16:06
Hello @angeloashmore, since yesterday, we've got an error message, which seems to point to something different.

Here is a detailed screenshot including : 
* The error message,
* The detail of the `preview` endpoint response, with the specific resource that don't seem to fit the schema.

Note : I don't think there is any possibility that the Custom type schema is **really** divergent with what I fed the plugin : I'm using the Custom types API to fetch it automatically (with `customTypesApiToken`) and just rebuilt entirely the website multiple times.

![Screenshot 2021-08-23 at 17 59 56](https://user-images.githubusercontent.com/32556322/130480326-181224f6-09bf-4c2d-86aa-51248eb62ba3.png)

**Comment by angeloashmore** [comment] 2021-08-24 02:30
@benjaminwaterlot Thanks for the details. When the preview plugin processes a link, it does the following check:

```ts
export const valueRefinement = (value: unknown): value is prismicT.LinkField =>
  typeof value === 'object' && value !== null && 'link_type' in value
```

If that function returns false for the link field, the error in your screenshot will appear.

`{ link_type: "Document" }` would pass that test, so there must be another field somewhere that is failing. Is it possible to check all `page_landing` documents for that link? You can quickly check all your documents using GraphiQL (<http://localhost:8000/___graphql>) with this query:

```graphql
query {
  allPrismicPageLanding {
    nodes {
      uid
      data {
        partner_logo {
          raw
        }
      }
    }
  }
}
```

In the `raw` field, do you see anything that does not include a `link_type` field?

Thank you!

**Comment by benjaminwaterlot** [comment] 2021-08-24 08:11
Thanks @angeloashmore, there it was indeed. 

I have plenty of "good" elements (just like the one in my screenshot) and a single one that was `"partner_logo": null`.

I simply added a document in the Prismic UI for the wrong entity and it fixed the problem.

**Note** : I guess that still is an important bug because the preview API should not be able to return data not fitting the schema, right ?

---

```
// GOOD
        {
          "uid": "ouverture",
          "data": {
            "partner_logo": {
              "raw": {
                "link_type": "Document"
              }
            }
          }
        },
// GOOD TOO
        {
          "uid": "vocation",
          "data": {
            "partner_logo": {
              "raw": {
                "id": "YNyVXxIAACkAaX7u",
                "type": "element_image",
                "tags": [
                  "Remove before release"
                ],
                "slug": "untitled-document",
                "lang": "fr-fr",
                "first_publication_date": "2021-06-30T16:01:38+0000",
                "last_publication_date": "2021-06-30T16:01:38+0000",
                "link_type": "Document",
                "isBroken": false
              }
            }
          }
        },

// BAD
        {
          "uid": "playground",
          "data": {
            "partner_logo": null
          }
        }
```

**Comment by angeloashmore** [comment] 2021-08-24 20:30
Ah, good find. Thank you for checking that!

Yes, this is still a bug since `null` is a valid value. The plugin currently does *not* see it as valid and throws an error. I'll make this change and publish a new version.

**Comment by angeloashmore** [comment] 2021-08-25 02:19
@benjaminwaterlot I published a fix for your issue. Could you try the latest versions?

- `gatsby-source-prismic`: `v4.1.2`
- `gatsby-plugin-prismic-previews`: `v4.1.2`

Thanks again for finding that bug. 🙂

**Comment by angeloashmore** [comment] 2021-09-01 23:37
I'm going to close this now since the preview issue has been resolved. Thanks for your patience on this!

**Closed by angeloashmore** 2021-09-01 23:37 UTC
Labels: bug, V4
