### ISSUE TITLE
Gatsby 5

### ISSUE THREAD

**Issue by Primajin** [prismicio/prismic-gatsby#522] opened 2022-11-26 13:28 UTC
### Is your feature request related to a problem? Please describe.
I'd like to upgrade to v5 and prismic is the only plugin left that only supports 4.

### Describe the solution you'd like

Upgrade to support v5 Gatsby.

### Describe alternatives you've considered

Downgrade all plugins until prismic is ready...

### Additional context

https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/

**Comment by angeloashmore** [comment] 2022-11-27 00:57
Hi @Primajin, a new version of `gatsby-source-prismic` and `gatsby-plugin-prismic-previews` is in the works and will be out sometime in December or early January. The updated plugins include Gatsby 5 support, as well as several performance improvements.

Have you tried using the current latest version with Gatsby 5? You will need to use `npm i --legacy-peer-deps` since both Prismic plugins only declare Gatsby 4 compatibility, but I believe the plugins should work under Gatsby 5.

**Comment by Primajin** [comment] 2022-11-27 06:21
Hey @angeloashmore Thanks a lot for the info.
While `--legacy-peer-deps` seems to work fine locally it will break in GitHub CI and Gatsby Cloud - I will see if I can wield a hammer at it until it works - otherwise I'll wait for you folks 🤞🏻 

Thanks a lot for this plugin and have a great holiday season!

**Comment by grahamd711** [comment] 2022-12-27 22:33
hi @angeloashmore - thanks for your work on this plugin. do you have any more updates regarding release timeline for the new versions of `gatsby-source-prismic` and`gatsby-plugin-prismic-previews`?

**Comment by TannerJuby1** [comment] 2023-01-09 20:25
@angeloashmore Hello, is there still a planned release coming soon? I see you say December or early January but there hasn't been an update just yet...

Thanks

**Comment by davideghz** [comment] 2023-01-20 15:55
still WIP?

**Comment by thannes** [comment] 2023-01-27 19:47
any update?

**Comment by maheshsamudra** [comment] 2023-02-07 06:53
> Hi @Primajin, a new version of `gatsby-source-prismic` and `gatsby-plugin-prismic-previews` is in the works and will be out sometime in December or early January. The updated plugins include Gatsby 5 support, as well as several performance improvements.
> 
> Have you tried using the current latest version with Gatsby 5? You will need to use `npm i --legacy-peer-deps` since both Prismic plugins only declare Gatsby 4 compatibility, but I believe the plugins should work under Gatsby 5.

Any update on this?

**Comment by Primajin** [comment] 2023-02-26 15:26
Since there is no update here, you might want to follow along here as well: https://community.prismic.io/t/prismic-and-gatsby-5-incompatibility-issues/12485/3

(though there is no new information there as well, yet)

**Comment by angeloashmore** [comment] 2023-03-22 22:28
Hi everyone,

I realize I left everyone here in the dark, and I apologize for that.

As shared in the [forum post linked above](https://community.prismic.io/t/prismic-and-gatsby-5-incompatibility-issues/12485/3), development of the refreshed plugins has been put on pause since the development team and I have been shifted to other projects.

In the meantime, a quick update was published for the existing plugins to officially support Gatsby 5 (thank you for posting that message, @jodiedoubleday!). The plugins did not need any technical changes, but I confirmed they work with Gatsby 5 and updated the `peerDependencies` version accordingly.

We plan to resume work on the Gatsby plugins in the upcoming months. I would love to release them soon just as much as I'm sure you all want to use them. 😄

More details are shared in this forum thread where you can subscribe to get updates: https://community.prismic.io/t/use-prismic-with-gatsby-v5-today/12752

Thank you all for your patience, and again, I'm sorry for the lack of communication here.

**Comment by angeloashmore** [comment] 2023-03-22 22:29
I'm going to close this thread since the plugins can now be used with Gatsby 5 as of `v5.3.0`.

Development of the larger rewrite is ongoing. For more details on what those big changes include, see this issue: https://github.com/prismicio/prismic-gatsby/issues/514

**Closed by angeloashmore** 2023-03-22 22:29 UTC
Labels: enhancement

**Comment by Primajin** [comment] 2023-04-01 12:57
Thanks @angeloashmore, I can confirm it works 👌🏻
